services:
  - type: web
    name: xewxew
    runtime: docker # spécifie la runtime, adapte-le en fonction de ton backend (ex : node pour Node.js)
    plan: free
    dockerfilePath: Dockerfile
    buildCommand: "pip install -r requirements.txt" # commande d’installation des dépendances
    startCommand: "gunicorn MonBackend.wsgi:application" # commande pour démarrer l'application
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: xew_xew
          property: connectionString # utilise la base de données configurée

databases:
  - name: xew_xew
    plan: free
